export const ModulationOutputs = {
  Bpm: 'Bpm',
  Attack: 'Attack',
  Decay: 'Decay',
  Sustain: 'Sustain',
  Release: 'Release',
  GlobalFilter: 'GlobalFilter',
  ReverbGain: 'ReverbGain',
  ReverbMorph: 'ReverbMorph',
  WaveformMorph: 'WaveformMorph',
  DelayTime: 'DelayTime',
  DelayFilter: 'DelayFilter',
  DelayFeedback: 'DelayFeedback',
  DelayGain: 'DelayGain',
  Distortion: 'Distortion',
  Compressor: 'Compressor',
  LocalGain: 'LocalGain',
  GlobalGain: 'GlobalGain',
  Osc1Frequency: 'Osc1Frequency',
  Osc2Frequency: 'Osc2Frequency',
  Osc3Frequency: 'Osc3Frequency',
  Osc4Frequency: 'Osc4Frequency',
  Osc5Frequency: 'Osc5Frequency',
  Osc6Frequency: 'Osc6Frequency',
  Osc7Frequency: 'Osc7Frequency',
};
